export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  ResetPassword: { token: string };
  Onboarding: undefined;
  Home: undefined;
  BookDetail: { bookId: string };
  CategoryBooks: { categoryId: string; categoryName: string };
  ReadingSession: { bookId: string; planId?: string; isEdit?: boolean };
  ReadingPlan: { bookId: string; planId?: string; isEdit?: boolean };
  MediaViewer: { bookId: string; type: 'audio' | 'pdf' };
  Settings: undefined;
  Profile: undefined;
  Search: undefined;
  LanguageSettings: undefined;
  ThemeSettings: undefined;
  Notifications: undefined;
  About: undefined;
  AuthorProfile: { authorId: number };
  AddBook: { bookId?: string };
  AddFriends: undefined;
  Leaderboard: undefined;
  Challenges: undefined;
  ChallengeDetail: { challengeId: string };
  Stats: undefined;
  Achievements: undefined;
  Badges: undefined;
  GroupDetail: { groupId: number };
  CommunityDetail: { communityId: number };
  GroupMembers: { groupId: number };
  GroupDiscussions: { groupId: number };
  Discussion: { discussionId: number };
  CommunityMembers: { communityId: number };
  CommunityPosts: { communityId: number };
  Post: { postId: number };
  EditReadingPlan: { planId?: string; bookId?: string };
};
